[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/registrations"
  to = "/.netlify/functions/registrations"
  status = 200

[[redirects]]
  from = "/api/registrations/*"
  to = "/.netlify/functions/registrations-id"
  status = 200

[[redirects]]
  from = "/api/dashboard/stats"
  to = "/.netlify/functions/dashboard-stats"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
